### ISSUE TITLE
Elements are hard coded HTTP

### ISSUE THREAD

**Issue by ChadOhman** [linuxserver/docker-projectsend#13]
## Expected Behavior
All elements to load over Kubernetes load balancer

## Current Behavior
Some elements are causing a mixed content error causing modern browsers to block the insecure content.

## Steps to Reproduce
Live example: [https://send.lambnet.ca/](https://send.lambnet.ca/)

## Environment
**OS:** dok8s 1.16.2-do.0
**CPU architecture:** x86_64    
**How docker service was installed:**      
DigitalOcean Kubernetes deployment with Rancher, nginx ingress controller/DO load balancer, and cert-manager v0.11.0

## Docker logs
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.244.2.174. Set the 'ServerName' directive globally to suppress this message`

![2019-11-15 00_58_05-](https://user-images.githubusercontent.com/2351/68927114-47ae5780-0744-11ea-8ae8-11f51f07cfc5.png)

**Comment by aptalca** [comment]
This really looks like an issue with your set headers in your reverse proxy config

**Comment by ChadOhman** [comment]
Thanks for the reply. I was able to change the base url in the config file and this solved the problem.
