### ISSUE TITLE
support for newest release r1070

### ISSUE THREAD

**Issue by gbolo** [linuxserver/docker-projectsend#14]
Any plans to support this latest release? Currently the call to `https://api.github.com/repos/projectsend/projectsend/releases/latest` does not contain this release, so not sure what the best approach is for you to maintain this. I guess the projectsend git repo should mark this as the latest release.

**Comment by thelamer** [comment]
REF: https://github.com/linuxserver/docker-projectsend/pull/15
https://github.com/projectsend/projectsend/issues/743

Closing as php7/3.11 rebase should pull latest when merged.
