### ISSUE TITLE
Add ProjectSend Translations

### ISSUE THREAD

**Issue by corentiny1** [linuxserver/docker-projectsend#24]
## Desired Behavior
ProjectSend includes translation : 72 available languages ( https://www.projectsend.org/translations/index.php )
But the linuxserver docker image not expose "lang" and "templates/TEMPLATE_NAME/lang" folders.
Request : Add ProjectSend translation

## Current Behavior
English only : 
Web app :
![Capture d’écran 2021-12-12 175032](https://user-images.githubusercontent.com/221623/145721489-f672a55a-a811-4d0a-958f-8c80b41730ae.jpg)
Docker container :
![Capture d’écran 2021-12-12 174749](https://user-images.githubusercontent.com/221623/145721392-2c299e77-f846-4367-9d53-95e8a7eb2d3a.jpg)
![Capture d’écran 2021-12-12 174946](https://user-images.githubusercontent.com/221623/145721465-682d56f3-f970-46f0-9b45-9e229ec0d02f.jpg)

Docker compose : 
When I try to add the translation manually with 
volumes: 
      - /home/USER/project-send/lang:/app/projectsend/lang
      - /home/USER/project-send/templates:/app/projectsend/templates
The app doesn't start.
In the container I see something wrong (only 4 folders) : 
![Capture d’écran 2021-12-12 181347](https://user-images.githubusercontent.com/221623/145722343-2a1f1083-c6b7-4a5b-a245-99195f3d1029.jpg)
And I suppose to see this : 
![Capture d’écran 2021-12-12 181542](https://user-images.githubusercontent.com/221623/145722378-1eef51ff-5d9f-4e6c-8836-132cde0d99f4.jpg)

## Alternatives Considered
First solution : Manually
- Expose folders needed for adding new translations : "lang" and "templates"
- Add a new environment variable : "SITE_LANG" ( https://www.projectsend.org/how-to-use-translation-files/ ) 
- Manually download the zip, upload on the host machine, unzip in folders

Second solution : Auto
- Add a new variable : "DOWNLOAD_LANG" = ["https://www.projectsend.org/translations/get.php?lang=fr", "https://www.projectsend.org/translations/get.php?lang=pt_BR"] for example
- That will download the two translation files from projectsend website
- Unzip all files
- Add a new environment variable : "SITE_LANG"

**Comment by TheSpad** [comment]
@corentiny1 please give `lspipepr/projectsend:r1335-pkg-a2959a99-pr-25` a test. No ENV as it stands (need to edit the config file) but the translation directories are all symlinked to /config/translations now. Note that you don't need to create `lang` subdirectories for any of them.

**Comment by fatihboy** [comment]
@thespad works fine for my case. Thank you.

**Comment by ilexpl01** [comment]
> @corentiny1 please give `lspipepr/projectsend:r1335-pkg-a2959a99-pr-25` a test. No ENV as it stands (need to edit the config file) but the translation directories are all symlinked to /config/translations now. Note that you don't need to create `lang` subdirectories for any of them.

Hi.

Have installed newest version r1420. See no folder translations under /config directory :/

What do I do wrong ?

BR
