### ISSUE TITLE
[FEAT] Incorporate Let's Encrypt

### ISSUE THREAD

**Issue by pawisoon** [linuxserver/docker-projectsend#32]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be great if we could get Let's Encrypt as part of the setup of projectsend.

### Reason for change

Provides SSL enabled service and secure file sharing.

**Comment by Roxedus** [comment]
This doesn't seem to be function in ProjectSend today, and this is not the place for upstream feature requests. 

We do however recommend you to deploy a reverse proxy in front of all the applications you expose on the internet, which also should handle termination of TLS. We offer [linuxserver/swag](https://github.com/linuxserver/docker-swag) for that purpose, but you are free to use a reverse proxy of your choice.
