### ISSUE TITLE
[BUG] Cannot create a bind mount to /app/www/public/upload/files

### ISSUE THREAD

**Issue by Daniel-Kalus** [linuxserver/docker-projectsend#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to drop files into the /app/www/public/upload/files folder, so I can use the "find orphaned files" feature of projectsend. As I understand it, this would allow me to instantly upload big files, without using the web interface.

When I add this bind mount under volumes section:
`- $STORAGEDIR/appdata/filedrop/:/app/www/public/upload/files`
the container won't start up properly, because the files in /app/www/public/ don't get created. On the browser I get 403 Forbidden.
When I check the folder inside the container I see 
`root@6ea140ebcf61:/app/www/public# ls`
`lang  public-tmp  upload`
All the files which should be in the public folder are in public-tmp.

### Expected Behavior

The files and folders under /app/www/public/ should not be affected by a bind mount to /app/www/public/upload/files
...or any other solution which let's me bind mount that folder

### Steps To Reproduce

1. add bind mount under volumes section: - <some path>:/app/www/public/upload/files
2. start the container

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose -f projectsend.yml up -d
```

### Container logs

```bash
docker logs projectsend
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
New container detected. Setting up app folder and fixing permissions.
ln: failed to create symbolic link '/app/www/public/includes/sys.config.php': No such file or directory
date: '/app/www/public/lang/*': No such file or directory
date: '/config/translations/lang/*': No such file or directory
cp: cannot stat '/app/www/public/lang/*': No such file or directory
mv: cannot stat '/app/www/public/templates/default/lang': No such file or directory
mv: cannot stat '/app/www/public/templates/gallery/lang': No such file or directory
mv: cannot stat '/app/www/public/templates/pinboxes/lang': No such file or directory
[custom-init] No custom files found, skipping...
crontab: can't open 'abc': No such file or directory
[ls.io-init] done.
```

**Comment by Roxedus** [comment]
you want the documented /data mount.

**Comment by Daniel-Kalus** [comment]
Yes under the /data mount I can find the files I upload via the web interface. But there is the "Find orphan files" option in the "Files" section which I would like to use. On that page it states: "There are no files available to add right now. To use this feature you need to upload your files via FTP to the folder /app/www/public/upload/files". Unfortunately I cannot mount the mentioned folder, as described in the first post..

**Comment by Daniel-Kalus** [comment]
Aaah after looking at the Dockerfile I realised that /app/www/public/upload/files is available under /data/projectsend/files
Thanks alot!
