### ISSUE TITLE
Translation in transifex

### ISSUE THREAD

**Issue by NexusEFR** [linuxserver/docker-projectsend#39]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I have translated several strings on the platform, but the missing translations for Spanish ES are not showing up after the latest updates. Why are they not appearing? There are certain parts where all the texts have not been translated yet. Thank you for the help and congratulations on the excellent project that Projectsend is. Regards.

### Reason for change

Important strings are missing both on the administration side and on the client side, which creates some confusion with the language

**Comment by j0nnymoe** [comment]
I suspect you need to report this to the upstream project, not us as we just package what they release.

**Comment by NexusEFR** [comment]
Ok, thanks, posted again there

**Comment by NexusEFR** [comment]
The problem is that no one responds and the projectsend docker is unattended, it seems that they don't follow up much on the reported issues. No one has answered my simple query about why the translation changes are not applied in transifex and then in the dockerhub releases... Honestly, it seems that the project is starting to be abandoned by the development team. It's possible?
