### ISSUE TITLE
Fresh install not working with r1053 version

### ISSUE THREAD

**Issue by sparklyballs** [linuxserver/docker-projectsend#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

upon fresh install since r1053 version using the make config link results in the following 

![screen shot 2018-06-11 at 16 26 13](https://user-images.githubusercontent.com/4343808/41241410-c3ff87b4-6d94-11e8-84c4-48b72b83c69b.png)

not sure of the fix yet..

**Comment by tomkuba** [comment]
I am not sure where is the problem, but here is a workaround to get r1053 up and running:
1. start linuxserver/projectsend:76 image (version r756 of ProjectSend)
2. create a config file using /install/make-config.php address
3. upgrade to latest docker image and continue with installation.

**Comment by CHBMB** [comment]
Closing this as issue no longer present.

**Comment by CHBMB** [comment]
Fixed in either https://github.com/linuxserver/docker-projectsend/pull/9 with some changes or with this https://github.com/linuxserver/docker-projectsend/pull/12

**Comment by thelamer** [comment]
This can be closed as the app does present a setup screen by default, the linked PR is to add setting this up by env.
